/**
 * Strings UI iCV (FR). Verbatim SPECS_FEATURE_ICV.md.
 */

export const icv = {
  title: "iCV",
  subtitle: "Créez et personnalisez votre CV professionnel",
  actions: {
    edit: "Modifier",
    import: "Importer",
    pdf: "PDF",
    preparing: "Préparation...",
    pdfReady: "📄 PDF prêt",
    pdfReadyDesc: "Le téléchargement va démarrer.",
    rateLimitPdf: "Limite d'exports atteinte. Réessayez demain.",
    renderFailed: "Échec de la génération. Réessayez ou contactez le support.",
  },
  selector: {
    principalBadge: "Principal",
    sourceManual: "Manuel",
    sourceOnboarding: "Initial",
    sourceAiOptimize: "Variant IA",
    sourceImport: "Importé",
    newCv: "+ Nouveau CV",
    viewAll: "Voir tous mes CV",
    derivedFrom: (name: string) => `Variant de : ${name}`,
  },
  themes: {
    title: "Choisir un thème",
    activeIndicator: "Thème actif",
    gallery: "Galerie des thèmes",
    galleryDesc: "12 mises en page, 3 catégories — appliquées à votre CV.",
    apply: (label: string) => `Appliquer ${label}`,
  },
  aiTools: {
    title: "Options IA",
    cardTitle: "Suggestion de l'IA :",
    accept: "Accepter",
    ignore: "Ignorer",
    inProgress: "Génération en cours...",
    failed: "L'outil IA a échoué. Réessayez.",
    quotaExceeded: "Quota IA quotidien atteint (10/jour). Réessayez demain.",
  },
  profile: {
    eyebrow: "MON PROFIL",
    experiencesCount: (n: number) => `${n} exp.`,
    skillsCount: (n: number) => `${n} comp.`,
  },
  preview: {
    a4Footer: "A4 · 210×297 mm",
  },
  studio: {
    done: "Terminé",
    backToDashboard: "Retour au tableau de bord",
    zoomIn: "Agrandir",
    zoomOut: "Réduire",
  },
  list: {
    title: "Mes CV",
    description: "Tous vos CV au même endroit",
    newCv: "+ Nouveau CV",
    limitReached: "Limite de 10 CV atteinte",
    actions: {
      open: "Ouvrir",
      rename: "Renommer",
      duplicate: "Dupliquer",
      setDefault: "Définir comme principal",
      download: "Télécharger en PDF",
      remove: "Supprimer",
    },
    confirmRemove: (name: string) =>
      `Supprimer le CV « ${name} » ? Cette action est irréversible (soft delete — il peut être restauré dans les paramètres).`,
    cannotDeleteDefault:
      "Impossible de supprimer le CV principal. Désignez d'abord un autre CV comme principal.",
    empty: {
      title: "Vous n'avez pas encore de CV.",
      cta: "Démarrer mon premier CV",
    },
    updatedAt: (date: string) => `Modifié le ${date}`,
  },
  create: {
    title: "Créer un CV",
    nameLabel: "Nom du CV",
    namePlaceholder: "ex. CV Tech, CV Direction…",
    copyFromLabel: "Partir d'un CV existant",
    copyFromEmpty: "— (CV vierge)",
    cancel: "Annuler",
    create: "Créer",
  },
  rename: {
    title: "Renommer le CV",
    nameLabel: "Nouveau nom",
    cancel: "Annuler",
    save: "Enregistrer",
  },
  dashboard: {
    title: "Tableau de bord iCV",
    subtitle: (lastUpdate: string, name: string) =>
      `Mis à jour ${lastUpdate} · ${name}`,
    lastUpdateToday: "aujourd'hui",
    lastUpdateYesterday: "hier",
    lastUpdateOlder: (date: string) => `le ${date}`,
    score: "SCORE",
    levelExpert: "Niveau Expert",
    levelGood: "Niveau Bon",
    levelBeginner: "Niveau Débutant",
    descExpert: "Profil attractif",
    descGood: "Bon profil — quelques améliorations possibles",
    descBeginner: "Profil à compléter",
    suggestionsTitle: "SUGGESTIONS",
    sectionsTitle: "SECTIONS DU CV",
    currentPreviewTitle: "APERÇU ACTUEL",
    themeLabel: (label: string) => `Thème · ${label}`,
    changeTheme: "Changer de thème",
    editCv: "Modifier mon CV",
    downloadPdf: "Télécharger PDF",
    share: "Partager",
    shareComingSoon: "Bientôt disponible",
  },
  editor: {
    eyebrow: "ICV · ÉDITION",
    cancel: "Annuler",
    save: "Enregistrer les modifications",
    sections: {
      experience: {
        addTitle: "Ajouter une expérience",
        editTitle: "Modifier une expérience",
        fields: {
          title: "Intitulé du poste",
          titlePh: "ex. Chef de Projet Digital",
          company: "Entreprise",
          companyPh: "ex. Agence Web Gabon",
          startDate: "Date de début",
          endDate: "Date de fin",
          endDatePh: "—",
          current: "Poste actuel",
          description: "Description",
        },
        aiImprove: "Améliorer avec l'IA",
      },
      education: {
        addTitle: "Ajouter une formation",
        editTitle: "Modifier une formation",
        fields: {
          degree: "Diplôme",
          school: "Établissement",
          year: "Année",
          description: "Description (optionnel)",
        },
      },
      skill: {
        addTitle: "Ajouter une compétence",
        editTitle: "Modifier une compétence",
        fields: {
          name: "Nom",
          level: "Niveau",
        },
        levels: {
          Débutant: "Débutant",
          Intermédiaire: "Intermédiaire",
          Avancé: "Avancé",
          Expert: "Expert",
        },
      },
      language: {
        addTitle: "Ajouter une langue",
        editTitle: "Modifier une langue",
        fields: {
          name: "Langue",
          level: "Niveau",
        },
      },
    },
  },
  import: {
    title: "Importer un CV",
    desc: "Vos données seront extraites et pré-remplies.",
    dropTitle: "Déposez votre CV",
    dropSpec: "PDF ou image · 5 Mo max.",
    browse: "Parcourir mes fichiers",
    modeLabel: "Que faire de l'import ?",
    modeNew: "Créer un nouveau CV",
    modeMerge: "Fusionner avec le CV actif",
    importing: "Import en cours...",
    success: "📥 Import réussi",
    successDesc: "Les données ont été importées.",
    failed: "L'import a échoué. Vérifiez le fichier et réessayez.",
    cancel: "Annuler",
    submit: "Lancer l'import",
  },
  ats: {
    title: "Score ATS",
    desc: "Compatibilité avec les systèmes de recrutement",
    resultEyebrow: "RÉSULTAT",
    resultGood: "Bien optimisé",
    resultMid: "À améliorer",
    resultBad: "Faiblement optimisé",
    resultDesc:
      "Votre CV est bien optimisé pour les systèmes de recrutement automatique.",
    later: "Plus tard",
    optimize: "Optimiser mon CV",
  },
  optimizeJob: {
    title: "Optimiser pour un poste",
    desc: "Collez l'offre — l'IA crée un nouveau CV adapté.",
    offerLabel: "Texte de l'offre",
    offerPh: "Collez ici la description du poste visé...",
    nameLabel: "Nom du nouveau CV (optionnel)",
    namePh: "Variant — Chef de projet",
    cancel: "Annuler",
    submit: "Optimiser",
    running: "Optimisation en cours...",
    success: "✨ CV optimisé créé",
    successDesc: "Vous êtes redirigé vers le nouveau CV.",
  },
  errors: {
    loadFailed: "Impossible de charger ce CV.",
    saveFailed: "Échec de l'enregistrement.",
    rateLimited: "Trop de requêtes. Réessayez dans quelques instants.",
  },
}
